package com.tadhack.orlandoappointment.orlandoappointment.model;// default package
// Generated Mar 10, 2018 3:27:23 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "appointments", catalog = "orlandoappointmentdb")
public class Appointments implements java.io.Serializable {

	private int idappointment;
	private Customer customer;
	private Professional professional;
	private TimeSlot timeSlot;
	private Date date;
	private Date time;
	private Integer duration;

	public Appointments() {
	}

	public Appointments(int idappointment, Customer customer, Professional professional, TimeSlot timeSlot) {
		this.idappointment = idappointment;
		this.customer = customer;
		this.professional = professional;
		this.timeSlot = timeSlot;
	}

	public Appointments(int idappointment, Customer customer, Professional professional, TimeSlot timeSlot, Date date,
			Date time, Integer duration) {
		this.idappointment = idappointment;
		this.customer = customer;
		this.professional = professional;
		this.timeSlot = timeSlot;
		this.date = date;
		this.time = time;
		this.duration = duration;
	}

	@Id

	@Column(name = "idappointment", unique = true, nullable = false)
	public int getIdappointment() {
		return this.idappointment;
	}

	public void setIdappointment(int idappointment) {
		this.idappointment = idappointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_idcustomer", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "professional_idprofessional", nullable = false)
	public Professional getProfessional() {
		return this.professional;
	}

	public void setProfessional(Professional professional) {
		this.professional = professional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_slot_idtime_slot", nullable = false)
	public TimeSlot getTimeSlot() {
		return this.timeSlot;
	}

	public void setTimeSlot(TimeSlot timeSlot) {
		this.timeSlot = timeSlot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

}
