package com.tadhack.orlandoappointment.orlandoappointment.model;// default package
// Generated Mar 10, 2018 3:27:23 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AvailableTime generated by hbm2java
 */
@Entity
@Table(name = "available_time", catalog = "orlandoappointmentdb")
public class AvailableTime implements java.io.Serializable {

	private int idavailableTime;
	private Professional professional;
	private Date date;
	private Long startTime;
	private Long edndTime;

	public AvailableTime() {
	}

	public AvailableTime(int idavailableTime, Professional professional) {
		this.idavailableTime = idavailableTime;
		this.professional = professional;
	}

	public AvailableTime(int idavailableTime, Professional professional, Date date, Long startTime, Long edndTime) {
		this.idavailableTime = idavailableTime;
		this.professional = professional;
		this.date = date;
		this.startTime = startTime;
		this.edndTime = edndTime;
	}

	@Id

	@Column(name = "idavailable_time", unique = true, nullable = false)
	public int getIdavailableTime() {
		return this.idavailableTime;
	}

	public void setIdavailableTime(int idavailableTime) {
		this.idavailableTime = idavailableTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "professional_idprofessional", nullable = false)
	public Professional getProfessional() {
		return this.professional;
	}

	public void setProfessional(Professional professional) {
		this.professional = professional;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "start_time", precision = 10, scale = 0)
	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	@Column(name = "ednd_time", precision = 10, scale = 0)
	public Long getEdndTime() {
		return this.edndTime;
	}

	public void setEdndTime(Long edndTime) {
		this.edndTime = edndTime;
	}

}
