package com.tadhack.orlandoappointment.orlandoappointment.model;// default package
// Generated Mar 10, 2018 3:27:23 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "orlandoappointmentdb")
public class Company implements java.io.Serializable {

	private int idcompany;
	private Category category;
	private String companyName;
	private String state;
	private String zipCode;
	private String city;
	private String phonenumber;
	private String email;
	private String url;
	private Set<Professional> professionals = new HashSet<Professional>(0);

	public Company() {
	}

	public Company(int idcompany, Category category) {
		this.idcompany = idcompany;
		this.category = category;
	}

	public Company(int idcompany, Category category, String companyName, String state, String zipCode, String city,
			String phonenumber, String email, String url, Set<Professional> professionals) {
		this.idcompany = idcompany;
		this.category = category;
		this.companyName = companyName;
		this.state = state;
		this.zipCode = zipCode;
		this.city = city;
		this.phonenumber = phonenumber;
		this.email = email;
		this.url = url;
		this.professionals = professionals;
	}

	@Id

	@Column(name = "idcompany", unique = true, nullable = false)
	public int getIdcompany() {
		return this.idcompany;
	}

	public void setIdcompany(int idcompany) {
		this.idcompany = idcompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "company_name", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip_code", length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "phonenumber", length = 50)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "url", length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Professional> getProfessionals() {
		return this.professionals;
	}

	public void setProfessionals(Set<Professional> professionals) {
		this.professionals = professionals;
	}

}
